### ISSUE TITLE
Can't sign in - CSS selectors are set right

### ISSUE THREAD

**Issue by sagistrauss** [mrbirl/LinkedScrape#1]
Hi there,
I can't seem to login even though the CSS selectors are set to the correct names.
## Any ideas?

No past results loaded
Logging in...
<input name="submit" type="submit" value="Sign in"/>
Traceback (most recent call last):
  File "dryscraper_linkedin.py", line 298, in <module>
    scraper = LinkScrape(email, password, load_previous)
  File "dryscraper_linkedin.py", line 29, in **init**
    self.login()
  File "dryscraper_linkedin.py", line 236, in login
    signin.click()
TypeError: 'NoneType' object is not callable

**Comment by mrbirl** [comment]
It seems LinkedIn change their login page occasionally (maybe to try and stop things like this...!) - so I've frequently had to adjust this login part. To fix it'll need to be adjusted again to work with what their new page is looking for. Unfortunately I don't have much time right now to actively work on this, but if I get a chance I'll try and fix it soon. If you work it out please feel free to update :) 

I suspect if the CSS selectors are all correct, there's another check somewhere that's blocking it now. Will see if I can spot what's doing that.

**Comment by sagistrauss** [comment]
Hi Cian, I'm going to try and solve it myself - if I'll do, I'll commit some changes :)
Thanks!

**Comment by mrbirl** [comment]
Great, thanks, good luck with it!
